export enum NumberInputKeys {
	None = 'none',
	Nine = '9',
	Eight = '8',
	Seven = '7',
	Six = '6',
	Five = '5',
	Four = '4',
	Three = '3',
	Two = '2',
	One = '1',
	Zero = '0',
	Dot = '.',
	Minus = '-',
	BackSpace = 'Backspace',
	Enter = 'Enter',
	ZoomIn = 'zomein',
	ZoomOut = 'zomeout',
}